name: CMake on a single platform

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2025

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target MQALLOC --config ${{env.BUILD_TYPE}}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: 'build\Release\MQALLOC.dll'
